config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'

  get 'show/:permalink', to: 'public#show'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/escape_output'
  get 'demo/calendar'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  layout 'admin'


  before_action :confirm_logged_in, except: [:login, :attempt_login, :logout]

  def menu
    @user_name = session[:user_name]
  end

  def login
  end

  def attempt_login
    if params[:user_name].present? && params[:password].present?
      found_user = AdminUser.where(user_name: params[:user_name]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
      end
    end

    if authorized_user
      session[:user_id] = authorized_user.id
      session[:user_name] = authorized_user.user_name
      flash[:notice] = "You are now logged in"
      puts "Logged in *********"
      redirect_to(admin_path)
    else
      flash.now[:notice] = 'invalid username/password combination.'
      render('login')
    end
  end

  def logout
    session[:user_id] = nil
    session[:user_name] = nil
    flash[:notice] = "logged out"
    redirect_to(access_login_path)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/views/access/login.html.erb
<% @page_title = 'Admin Login' %>

<div class="login">
  <%= form_tag(access_attempt_login_path, method: :post) do %>
  <table>
    <tr>
      <td><%= label_tag :user_name %></td>
      <td><%= text_field_tag :user_name, params[:user_name] %></td>
    </tr>
    <tr>
      <td><%= label_tag :password %></td>
      <td><%= password_field_tag :password %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= submit_tag 'Log In' %></td>
    </tr>
  </table>
  <% end %>
</div>

app/views/access/menu.html.erb
<% @page_title = 'Admin Menu' %>

<div class="menu">
  <h2>Admin Menu</h2>
  <div class="identity">Logged in as: <%= @user_name %></div>
  <ul>
    <li><%= link_to 'Manage Subjects', subjects_path %></li>
    <li><%= link_to 'Manage Pages', pages_path %></li>
    <li><%= link_to 'Manage Sections', sections_path %></li>
    <li><%= link_to 'Manage Admin Users', admin_users_path %></li>
    <li><%= link_to 'Logout', access_logout_path %></li>
  </ul>
</div>