config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'

  get 'show/:permalink', to: 'public#show'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/escape_output'
  get 'demo/calendar'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table>
  <tr>
    <td>name</td>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <td>Permalink</td>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <td>Position</td>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <td>Visible</td>
    <td><%= f.check_box(:visible) %></td>
  </tr>
  <tr>
    <td>Subject type</td>
    <td><%= f.select :subject, options_for_select(@subjects.collect{|u| u.name}) %></td>
  </tr>
  <tr>
    <td>Submit</td>
    <td><%= f.submit('Save') %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<h2>Delete <%= @page.name %></h2>
<p>Are you sure you want to delete <%= @page.name %>?</p>
<%= form_for(@page, method: 'delete') do |f| %>
  <%= f.submit('Delete', class: 'Delete-button') %>
<% end  %>

app/views/pages/edit.html.erb
<h2>Edit Page</h2>
<%= form_for(@page) do |f| %>

  <%= render(partial: 'form', locals:{f: f}) %>

<% end  %>

app/views/pages/index.html.erb
<%= link_to '<<< Back to Admin Area', admin_path %><br/> 
<%= link_to('Create new Page', new_page_path, class: 'New-button') %>
<div class='pages-table'>
  <table>
    <tr>
      <th>Page</th>
      <th>Position</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.position %></td>
      <td><%= page.permalink %></td>
      <td><%= status_tag(page.visible) %></td>
      <td>
        <%= link_to('Show', page_path(page)) %>
        <%= link_to('Edit', edit_page_path(page)) %>
        <%= link_to('Delete', delete_page_path(page)) %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/pages/new.html.erb
<h2>Create new Page</h2>
<%= form_for(@page) do |f| %>

  <%= render(partial: 'form', locals:{f: f}) %>

<% end  %>

app/views/pages/show.html.erb
<%= link_to('<<< Back to Pages', pages_path) %>
<div class="show">
  <h2>Show Page</h2>
  <table class="show-table">
    <th>Page</th>
    <th>permalink</th>
    <th>position</th>
    <th>Created At</th>
    <th>Edit At</th>
    <tr>
      <td><%= @page.name %></td>
      <td><%= @page.permalink %></td>
      <td><%= @page.position %></td>
      <td><%= @page.created_at %></td>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>
</div>