config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'

  get 'show/:permalink', to: 'public#show'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/escape_output'
  get 'demo/calendar'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :pages

  scope :visible, -> { where(visible: true) }
  scope :invisible, -> { where(visible: false) }
  scope :sorted, -> { order('position ASC') }
  scope :newest_first, -> { order('created_at DESC') }
  scope :search, lambda { |query| where('name LIKE ?', "%#{query}%") }

  validates_presence_of :name
  validates_length_of :name, maximum: 255
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :count_subjects, only: [:new, :create, :edit, :update]

  layout 'admin'

  def index
    logger.debug('****** Testing the logger.******')
    @subjects = Subject.sorted
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      flash[:notice] = "Subject was created."
      redirect_to(subjects_path)
    else
      render('new')
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(subject_params)
      flash[:notice] = "Subject was Updated."
      redirect_to(subject_path(@subject))
    else
      render('edit')
    end
  end

  def delete
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Subject was Deleted."
    redirect_to(subjects_path)
  end

  private

  def subject_params
    params.require(:subject).permit(:name, :position, :visible, :created_at)
  end

  def count_subjects
    if params[:action] == 'new' || params[:action] == 'create'
      @subject_count = Subject.count + 1
    else
      @subject_count = Subject.count
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary='Subjects form fields'>
<tr>
  <th>Name</th>
  <td><%= f.text_field(:name)  %></td>
</tr>
<tr>
  <th>Position</th>
  <td><%= f.select(:position, 1..@subject_count) %></td>
</tr>
<tr>
  <th>Visible</th>
  <td><%= f.check_box(:visible) %></td>
</tr>
<tr>
  <%= f.datetime_select(:created_at, selected: Date.today, start_year: Date.today.year, end_year: Date.today.year+10, start_hour: Time.now.hour) %>
</tr>
  <tr>
    <td><%= f.submit('Create Subject') %></td>
  </tr>

app/views/subjects/delete.html.erb
<%= link_to('<< Return to List', subjects_path, class: 'back-button') %>

<%= form_for(@subject, method: 'delete') do |f| %>
  <h2>Delete Subject</h2>
  <p>Are you sure you want to delete <%= f.object.name %>?</p>
  <%= f.submit('delete', class: 'delete-button') %>
<% end %>

app/views/subjects/edit.html.erb
<%= link_to('<< Back to List', subjects_path, class: 'back-link') %>

<div class="subject-edit">
  <h2>Update Subject</h2>
  <%= form_for(@subject) do |f| %>

  <%= render( partial: 'form', locals: {f: f}) %>

  <% end %>
    </table>
</div>

app/views/subjects/index.html.erb
<%= link_to '<<< Back to Admin Area', admin_path %><br/> 
<div class="subjects_index">
  <h2>Subjects</h2>
  <%= image_tag 'plus_sign.png', size: '11x11', alt: '+' %>
  <%= link_to('Add New Subject', new_subject_path, class: 'action new') %>
  <table class="lisitng" summary='subject list'>
    <tr class="header">
      <th>#</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
  <% @subjects.each do |subject| %>
  <tr class="border">
    <td><%= subject.position %></td>
    <td><%= subject.name %></td>
    <td class="center"><%= status_tag(subject.visible) %></td>
    <td class="center"><%= subject.pages.size %></td>
    <td class="actions">
      <%= link_to('Show', subject_path(subject), class: 'action show') %>
      <%= link_to('Edit', edit_subject_path(subject), class: 'action edit') %>
      <%= link_to('Delete', delete_subject_path(subject), class: 'action delete') %>
    </td>
  </tr>
  <% end %>
</table>
</div>

app/views/subjects/new.html.erb
<%= link_to('<< Back to List', subjects_path, class: 'back-link') %>

<div class="subject-new">
  <h2>Create Subject</h2>
  <%= form_for(@subject) do |f| %>

  <%= render(partial: 'form', locals: {f: f}) %>

  <% end %>
    </table>
</div>

app/views/subjects/show.html.erb
<%= link_to('<< Back to List', subjects_path, class: 'back-link') %>


<div class="subjects-show">
  <h2>Show Subjects</h2>
  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @subject.visible %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at.strftime('%h-%d-%Y at %I:%M %p') %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at.strftime('%h-%d-%Y at %I:%M %p') %></td>
    </tr>
  </table>
</div>