config/routes.rb
Rails.application.routes.draw do
  root to: 'public#index'

  get 'show/:permalink', to: 'public#show'

  root 'demo#index'

  get 'admin', to: 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, except: [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/escape_output'
  get 'demo/calendar'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  has_secure_password
  # When changing table names must change pre-gen file names or points
  # self.table_name = "admin_users"

  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, through: :section_edits

scope :sorted, lambda { |column| order("LOWER(#{column})")}

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_USER_NAMES = %w(cgibsonmm suckatwat).freeze

  validates :first_name, presence: true,
                         length: { maximum: 25 }

  validates :last_name, presence: true,
                        length: { maximum: 50 }

  validates :user_name, presence: true,
                        length: { within: 8..25 },
                        uniqueness: true

  validates :email, presence: true,
                    length: { maximum: 100 },
                    format: { with: EMAIL_REGEX },
                    confirmation: true

  validate :user_name_is_allowed
  validate :no_new_users_on_monday, on: :create


    def name
      "#{first_name} #{last_name}"
    end

  private

  def user_name_is_allowed
    if FORBIDDEN_USER_NAMES.include?(user_name)
      errors.add(:user_name, 'has been restricted from use.')
    end
  end

  def no_new_users_on_monday
    if Time.now.sunday?
      errors.add(:base, "Can't create user today, please come back tomorrow.")
    end
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in

  def index
    @admin_users = AdminUser.sorted(:last_name).sorted(:first_name)
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_params)
    if @admin_user.save
      flash[:notice] = "New Admin created"
      redirect_to(admin_users_path)
    else
      logger.debug(@admin_user.errors.full_messages)
      flash[:notice] = @admin_user.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update(admin_params)
      flash[:notice] = "Admin Updated"
      redirect_to(admin_users_path)
    else
      flash[:notice] = "error updating user"
      render 'edit'
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "#{@admin_user.user_name} successfully deleted"
    redirect_to(admin_users_path)
  end


  private

  def admin_params
    params.require(:admin_user).permit(
        :first_name, :last_name, :user_name, :password, :email)
  end
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/delete.html.erb
<h2>Delete <%= @admin_user.user_name %></h2>

<p>are you sure you want to permently delete this admin</p>
<%= form_for @admin_user, method: :delete do |f| %>
  <%= f.submit "Delete" %>
<% end %>

app/views/admin_users/edit.html.erb
<h2>edit Admin User</h2>

<%= link_to '<<< Back to index', admin_users_path %>
<%= form_for @admin_user do |f| %>
  <table>
    <tr>
      <td><%= f.label :first_name %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <td><%= f.label :user_name %></td>
      <td><%= f.text_field :user_name %></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end  %>

app/views/admin_users/index.html.erb
<%= link_to '<<< Back to Admin Area', admin_path %><br/> 
<%= link_to 'Create new admin', new_admin_user_path %>
<table class="admin_users">
  <tr>
    <th>Last Name</th>
    <th>First Name</th>
    <th>User Name</th>
    <th>Created At</th>
    <th>Options</th>
  </tr>
  <% @admin_users.each do  |admin| %>
  <tr>
    <td><%= admin.last_name %></td>
    <td><%= admin.first_name %></td>
    <td><%= admin.user_name %></td>
    <td><%= admin.created_at.strftime('%m-%d-%y') %></td>
    <td>
      <%= link_to "Edit", edit_admin_user_path(admin) %>
      <%= link_to 'Delete', delete_admin_user_path(admin) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin_users/new.html.erb
<h2>Create Admin User</h2>

<%= link_to '<<< Back to index', admin_users_path %>
<%= form_for @admin_user do |f| %>
  <table>
    <tr>
      <td><%= f.label :first_name %></td>
      <td><%= f.text_field :first_name %></td>
    </tr>
    <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name %></td>
    </tr>
    <tr>
      <td><%= f.label :user_name %></td>
      <td><%= f.text_field :user_name %></td>
    </tr>
    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password %></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><%= f.submit %></td>
    </tr>
  </table>
<% end  %>